spring:
  application:
    name: demo
  profiles:
    active: test #默认为远程测试环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
#  redis:
#    database: 1 #redis数据库索引（默认为0）
#    host: localhost #redis服务器地址
#    port: 6379 #redis服务器连接端口
#    password: lyuanzhi #redis服务器连接密码
#    jedis:
#      pool:
#        max-active: 1000 #连接池最大连接数（-1代表没限制）
#        max-wait: -1 #连接池最大阻塞等待时间
#        max-idle: 10 #连接池中的最大空闲连接数
#        min-idle: 2 #连接池中的最小空闲连接数
#    timeout: 1000 #连接超时时间（毫秒）

# mybatis 配置
mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.jumbox.demo.mbg.pojo

# 通用 Mapper 配置
mapper:
  mappers: com.jumbox.demo.mbg.MyMapper
  not-empty: false
  identity: MYSQL

## Server 服务端配置
#server:
#  port: 443
#  servlet:
#    session:
#      timeout: 60 #session 最大超时时间（分钟），默认30分钟
#  error:
#    path: /error # 默认为 /error
#    whitelabel:
#      enabled: false #默认为 true，现在把它禁用
#  ssl:
#    key-store: classpath:lyuanzhi.com.jks
#    key-store-password: 4mzbg9rue9xtnhu
#    key-store-type: JKS

# war包配置到云服务器上：nohup java -jar lyzdemo.war &
# 查看 war包运行进程：lsof -i:80 或 ps aux|grep lyzdemo.war
# 关闭进程：kill -9 进程号（-9表示强制关闭进程）

